export const UPDATE_ONBOARDING_STATUS="UPDATE_ONBOARDING_STATUS";
export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const UPDATE_USER_ACCESS_TOKEN = "UPDATE_USER_ACCESS_TOKEN";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';
export const UPDATE_SELECTED_OPTION='UPDATE_SELECTED_OPTION';